name: Un Workflow para el primer parcial de BackEnd
on: push

jobs:
  build:
    name: parcial action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./parcial
        with:
          N_INDEX: "9"